### ISSUE TITLE
[EL9] Diff By FONT in /etc/vconsole.conf

### ISSUE THREAD

**Issue by DirectorSloan** [idiv-biodiversity/ansible-role-locale#4]
Bei einem Testlauf auf ein Rocky Linux 9 bekommt das Play `[idiv-biodiversity.locale : configure virtual console keyboard (/etc/vconsole.conf)]` folgenden Diff:

```
--- before: /etc/vconsole.conf
+++ after: /root/.ansible/tmp/ansible-local-212956v5qqcr9e/tmpb7z1625c/vconsole.conf.j2
@@ -1,2 +1 @@
 KEYMAP="de-nodeadkeys"
-FONT="eurlatgr"
```

Wollte ich einfach mal Festhalten bevor ich oder du handeln. Vermutlich einfach nochmal ein Varsplit bei `redhat.yml` von < 9 und >= 9

**Comment by wookietreiber** [comment]
Should be fixed in v0.4.0.
